<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Skudler\\' => array($vendorDir . '/skudler/skudler-api/src'),
);
